# Generated by Django 2.2.1 on 2019-05-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsv_file', models.FileField(upload_to='../../files/tsv/')),
                ('model_file', models.FileField(upload_to='../../files/model/')),
            ],
        ),
    ]
