# Generated by Django 2.2.1 on 2019-05-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190526_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='model_file',
            field=models.FileField(upload_to='files/model/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tsv_file',
            field=models.FileField(upload_to='files/tsv/'),
        ),
    ]
