# Generated by Django 2.2.1 on 2019-05-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190528_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
