# Generated by Django 2.2.1 on 2019-05-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20190528_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='result',
            new_name='Figure',
        ),
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='times',
            field=models.TextField(blank=True, null=True),
        ),
    ]
