# Generated by Django 2.2.1 on 2019-05-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20190528_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='times',
            new_name='time',
        ),
    ]
