# Generated by Django 2.2.1 on 2019-05-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20190528_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Figure',
            new_name='figure',
        ),
    ]
