# Generated by Django 2.2.1 on 2019-05-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20190528_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='figure',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='score',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
