# Generated by Django 2.2.1 on 2019-05-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20190528_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=20, null=True),
        ),
    ]
