# Generated by Django 2.2.1 on 2019-06-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20190531_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.TextField(default='admin_HC'),
        ),
    ]
