# Generated by Django 2.2.1 on 2019-06-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='admin_HC')),
                ('tsv_files', models.FileField(upload_to='files/tsv/')),
                ('model_file', models.FileField(upload_to='files/model/')),
                ('parameters', models.TextField()),
                ('score', models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=20, null=True)),
                ('time', models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=20, null=True)),
                ('optimized_model', models.FileField(blank=True, editable=False, null=True, upload_to='')),
                ('error', models.TextField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Calculation',
        ),
    ]
