# Generated by Django 2.2.1 on 2019-07-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20190627_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimization',
            name='parameters',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='optimization',
            name='score',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
