# Generated by Django 2.2.1 on 2019-07-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20190702_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimization',
            name='num_processes',
            field=models.DecimalField(blank=True, decimal_places=0, default=2, max_digits=3),
        ),
        migrations.AddField(
            model_name='optimization',
            name='tolerance',
            field=models.DecimalField(blank=True, decimal_places=9, default=0.0001, max_digits=10),
        ),
    ]
