# Generated by Django 2.2.1 on 2019-08-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20190705_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='admin_HC')),
                ('tsv_file', models.FileField(upload_to='files/tsv/')),
                ('model_file', models.FileField(upload_to='files/model/')),
                ('score', models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=20, null=True)),
                ('time', models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=20, null=True)),
                ('figure', models.TextField(blank=True, editable=False, null=True)),
                ('error', models.TextField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Calculation',
        ),
    ]
